---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dq-raw-message-retrieval
  annotations:
    environment: {{ .ENV }}
    {{ if eq .ENV "notprod" }}downscaler/uptime: Mon-Fri 07:00-18:30 Europe/London{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dq-raw-message-retrieval
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-raw-message-retrieval
    spec:
      containers:
      - name: dq-raw-message-retrieval
        image: quay.io/ukhomeofficedigital/dq-raw-message-retrieval:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dq-raw-message-retrieval
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dq-raw-message-retrieval
                key: AWS_SECRET_ACCESS_KEY
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: dq-raw-message-retrieval
                key: BUCKET_NAME
          - name: EXPOSED_PORT
            value: '3000'
        ports:
          - containerPort: 3000

      - name: keycloak-proxy
        image: quay.io/keycloak/keycloak-gatekeeper:10.0.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: PROXY_CLIENT_ID
            value: raw-message-retrieval
          - name: PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dq-raw-message-retrieval
                key: KEYCLOAK_CLIENT_SECRET
          - name: PROXY_LISTEN
            value: 0.0.0.0:8081
          - name: PROXY_DISCOVERY_URL
            valueFrom:
              secretKeyRef:
                name: dq-raw-message-retrieval
                key: KEYCLOAK_DISCOVERY
          - name: PROXY_UPSTREAM_URL
            value: http://127.0.0.1:3000
        args:
          - --resources
          - uri=/*|roles=tableau
          - --enable-logging
          - --enable-json-logging
          - --verbose

      - name: proxy
        image: quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect:b87
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8081'
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
